### ISSUE TITLE
bus-fill icon is black and not using currentColor

### ISSUE THREAD

**Issue by christophehurpeau** [phosphor-icons/core#12]
it seems to be the only icon with this issue

<img width="984" alt="image" src="https://github.com/phosphor-icons/core/assets/302891/ca346d2d-077d-465d-8068-29a839f4c0ea">

**Comment by christophehurpeau** [comment]
Also with "GearFine", both the regular and fill versions
<img width="1320" alt="image" src="https://github.com/phosphor-icons/core/assets/302891/248063e6-8d3b-416e-8949-4e911a44b849">

**Comment by rektdeckard** [comment]
Thanks for the report. Seems to be a bad export from Illustrator. As a temp workaround, these icons will still color properly if you set the `fill` attribute on the element.

**Comment by christophehurpeau** [comment]
@ttRmz
