### ISSUE TITLE
Sort descending / ascending wrong icon arrow direction

### ISSUE THREAD

**Issue by somebee** [phosphor-icons/core#13]
<img width="461" alt="image" src="https://github.com/phosphor-icons/core/assets/8467/57230877-1417-4c9b-9d7d-29dc93abfbf7">

This seems like a bug? Sort descending should clearly point down, and ascending should point up.

**Comment by rektdeckard** [comment]
You would think so, but this does seem to be the de-facto standard. The arrow points in the direction in which the sort value is increasing. For example, in Ascending order, values increase as you go *down* the list.

**Comment by rektdeckard** [comment]
Closing because this is intended behavior.

**Comment by somebee** [comment]
On mac, descending is arrow down, and ascending is arrow up.
<img width="202" alt="image" src="https://github.com/phosphor-icons/core/assets/8467/c93b2014-4068-4269-b9db-14155cad184d">
