### ISSUE TITLE
set stroke or fill to currentColor

### ISSUE THREAD

**Issue by tcoopman** [phosphor-icons/core#2]
it would be great if the svgs contain `stroke=currentColor` on the correct places to be able to use css properties to set the color of the icons.

**Comment by rektdeckard** [comment]
That's the intention! I did not tag this package as Beta, but it is still very much so and using assets directly from the current version of Phosphor (1.4). We'll have it squared away in the upcoming 2.0 release within a week or so.

**Comment by rektdeckard** [comment]
Done as of `v2.0.0` 👍
